name: pspdfkit_flutter
description: A Flutter plugin providing a feature-rich PDF viewing and editing experience to your users with the powerful PSPDFKit PDF SDK.
version: 3.12.0
homepage: https://pspdfkit.com/
repository: https://github.com/PSPDFKit/pspdfkit-flutter
issue_tracker: https://support.pspdfkit.com/hc/en-us/requests/new
documentation: https://pspdfkit.com/guides/flutter/
environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.16.9'

dependencies:
  build_runner: ^2.2.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  mockito: ^5.3.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.pspdfkit.flutter.pspdfkit
        pluginClass: PspdfkitPlugin
        fileName: src/pspdfkit_flutter_method_channel.dart
      ios:
        pluginClass: PspdfkitPlugin
        fileName: src/pspdfkit_flutter_method_channel.dart
      web:
        pluginClass: PspdfkitFlutterWeb
        fileName: src/pspdfkit_flutter_web.dart

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
